import Vue from "vue";

var json = Vue.extend({
  data: function() {
    return {
      count: 5,
      previous: null,
      results: [
        {
          id: 55944,
          event_id: 71790,
          name: "Session: iPads 101",
          starts: "2018-05-01T14:28:00",
          ends: "2018-05-05T14:28:00",
          capacity: 1000000,
          track_id: null,
          tags: [],
          access_control: false,
          auto_registration: false,
          hidden_session: false,
          overlap_enabled: true,
          overbook_capacity: 0,
          visibility: 0,
          broadcast_enabled: false,
          polls_enabled: false,
          poll_url: null,
          qa_url: null,
          chat_enabled: false,
          qa_enabled: false,
          is_live_viewers_numbers_hidden: false,
          poll_type: 0,
          viewer_counter_visibility: 0
        },
        {
          id: 55945,
          event_id: 71790,
          name: "Session: Kiosk Design Workshop",
          starts: "2018-05-01T14:28:00",
          ends: "2018-05-05T14:28:00",
          capacity: 1000000,
          track_id: null,
          tags: [],
          access_control: false,
          auto_registration: false,
          hidden_session: false,
          overlap_enabled: true,
          overbook_capacity: 0,
          visibility: 0,
          broadcast_enabled: false,
          polls_enabled: false,
          poll_url: null,
          qa_url: null,
          chat_enabled: false,
          qa_enabled: false,
          is_live_viewers_numbers_hidden: false,
          poll_type: 0,
          viewer_counter_visibility: 0
        },
        {
          id: 55946,
          event_id: 71790,
          name: "Session: Give me Data",
          starts: "2018-05-01T14:28:00",
          ends: "2018-05-05T14:28:00",
          capacity: 1000000,
          track_id: null,
          tags: [],
          access_control: false,
          auto_registration: false,
          hidden_session: false,
          overlap_enabled: true,
          overbook_capacity: 0,
          visibility: 0,
          broadcast_enabled: false,
          polls_enabled: false,
          poll_url: null,
          qa_url: null,
          chat_enabled: false,
          qa_enabled: false,
          is_live_viewers_numbers_hidden: false,
          poll_type: 0,
          viewer_counter_visibility: 0
        },
        {
          id: 55947,
          event_id: 71790,
          name: "Session: Generating a Lead",
          starts: "2018-05-01T14:28:00",
          ends: "2018-05-05T14:28:00",
          capacity: 1000000,
          track_id: null,
          tags: [],
          access_control: false,
          auto_registration: false,
          hidden_session: false,
          overlap_enabled: true,
          overbook_capacity: 0,
          visibility: 0,
          broadcast_enabled: false,
          polls_enabled: false,
          poll_url: null,
          qa_url: null,
          chat_enabled: false,
          qa_enabled: false,
          is_live_viewers_numbers_hidden: false,
          poll_type: 0,
          viewer_counter_visibility: 0
        },
        {
          id: 208331,
          event_id: 71790,
          name: "test-foo",
          starts: "2020-08-05T18:55:00",
          ends: "2020-08-20T10:55:00",
          capacity: 1000000,
          track_id: null,
          tags: [],
          access_control: false,
          auto_registration: false,
          hidden_session: false,
          overlap_enabled: true,
          overbook_capacity: 0,
          visibility: 0,
          broadcast_enabled: false,
          polls_enabled: false,
          poll_url: "",
          qa_url: null,
          chat_enabled: false,
          qa_enabled: false,
          is_live_viewers_numbers_hidden: false,
          poll_type: 0,
          viewer_counter_visibility: 0
        }
      ],
      next: null
    };
  }
});

module.exports = json;
